# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367f1e9ba9793c5205427fb5ea8df06da400033e224fce0c79d79e238db757588c2858ae31929c7f9465b21362ae0ac77fb06051daf5eaf1d2fdbd7219a1d3cd

test:
  secret_key_base: 00695c33d7a43c0a55583b9c459dd50074a5bc52fb5b73377dc2932e8eb9cc18ef13f9d6308fb4ff17a1af10f848460e4044f02ef62c59ea678b7d5e4a68dc5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
